### ISSUE TITLE
multiple BranchNodes and actualTask bug ?

### ISSUE THREAD

**Issue by MINIONBOTS** [tanema/behaviourtree.lua#6]
Hi there, 
I was playing around with your code and the moment I added two BranchNodes (Sequences) behind each other, it all went south ;)
```
local tree = BT:new({
	object = {name = 'test'},
       tree = BT.SequenceB:new({
    nodes = {
	 BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk left")
              success()
            end
          }),
			
		   BT.Sequence:new({
		   
				nodes = {
					BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk right")
              success()
            end
          }),
					BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk up")
              success()
            end
          }),
					}
				}
			),
			
		  BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk down")
              success()
            end
          }),
    }
  })
})
```

If I call run() on that tree, it goes into the first "walk left" node, then it goes into the 2nd node, which itself is again a sequence, runs the 1st child node "walk right" and the moment this child node finishes with success(), it continues in the "root-sequence" instead of the childnode's parent "sequence". 
I am starring at it now for several hours and adding more and more debug prints, but I cannot see the cause of the problem. It is like the "control" of the "walk right" node is being set to the root-selector instead of the actual parent selector node. 
Maybe you have an idea :)

**Comment by MINIONBOTS** [comment]
https://github.com/tanema/behaviourtree.lua/blob/master/examples/random.lua
Just take your example from here, replace the Random node with Sequence and add another 3rd Node in the 1st-root-sequence. 
It will process all 3 nodes from the 1st sequence and just 1 node, the 1st one, in the 2nd sequence.

**Comment by MINIONBOTS** [comment]
on 1st entry into the btree: 
function Node:call_run(object)
  success = function() self:success() end
  fail = function()    self:fail() end    
  running = function() self:fail() end
...

defines ONCE 3 GLOBAL variables, all pointing to the 1st root sequence. If anywhere in the tree any of these 3 varibales are called, they are always being executed on the root sequence level instead of the calling node.

**Comment by MINIONBOTS** [comment]
calling for example "running()" from a sub-node, should in theory pass the "self" of the sub-Node to the function. Instead, it uses the self of the root node where the running() function is defined the first time.
Lua 5.1 here.

**Comment by tanema** [comment]
Hey so this is a little "gotchya" of using this library and lua (at least how it is used here) Since I tried to make calls to success, fail, and running super easy to use without typing self: it works most of the time by just calling those methods. However sometimes the scope will be a bit different. Anyways without diving too deep into all of it I will just say scope your ending methods with self:. Here is a working version:

```lua
local BT = require('lib/behaviour_tree')

local tree = BT:new({
    object = {name = 'test'},
    tree = BT.Sequence:new({
    nodes = {
      BT.Task:new({
        run = function(self, object)
          print(object.name .. " walk left")
          self:success()
        end
      }),
      BT.Sequence:new({
        nodes = {
          BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk right")
              self:success()
            end
          }),
          BT.Task:new({
            run = function(self, object)
              print(object.name .. " walk up")
              self:success()
            end
          }),
        }
      }),
      BT.Task:new({
        run = function(self, object)
          print(object.name .. " walk down")
          self:success()
        end
      }),
    }
  })
})

tree:run()
```

**Comment by MINIONBOTS** [comment]
yes, self: is what has to be added.  
But "most of the time" equals "only if the tree has a depth of max 2" ;)
Anyway, thank you for this lib, it really helped me a lot :)
