### ISSUE TITLE
This doesn't seem to work.

### ISSUE THREAD

**Issue by piller187** [tanema/behaviourtree.lua#7]
I have the following tree def:

bt = BehaviourTree:new({
		tree = BehaviourTree.Priority:new({
			nodes = {
				BehaviourTree.Sequence:new({
					nodes = {
						"IsPredatorInRange",
						"RunAway"
					}
				})
			}
		})
	})

local task = BehaviourTree.Task:new({
	name = "IsPredatorInRange",

	start = function(task, obj)	
	end,

	finish = function(task, obj)
	end,

	run = function(task, obj)
		System:Print("Inside IsPreditorInRange return success")
		success()
		--fail()
	end
});

local task = BehaviourTree.Task:new({
	name = "RunAway",

	start = function(task, obj)	
	end,

	finish = function(task, obj)
	end,

	run = function(task, obj)
		System:Print("Inside RunAway return success")
		success()
		--fail()
	end
});

When I run this tree only IsPreditorInRange() prints out. RunAway task doesn't print which means it's not going into there which my understanding is that it should given IsPreditorInRange returns success and it's parent is a sequence.

**Comment by piller187** [comment]
Was able to validate that when the sequence isn't nested it calls both. So something about it being nested inside the Priority causes it to not call the next task in the list:

	self.bt = BehaviourTree:new({
		tree = BehaviourTree.Sequence:new({
				nodes = {
					"IsPredatorInRange",
					"RunAway"
				}
			})
	})

**Comment by tanema** [comment]
Go ahead and run this:

```lua
local BT = require('lib/behaviour_tree')

local bt = BT:new({
  tree = BT.Priority:new({
    nodes = {
      BT.Sequence:new({
        nodes = {
          "IsPredatorInRange",
          "RunAway"
        }
      })
    }
  })
})

local task = BT.Task:new({
	name = "IsPredatorInRange",

	start = function(self, obj)
	end,

	finish = function(self, obj)
	end,

	run = function(self, obj)
		print("Inside IsPreditorInRange return success")
		self:success()
	end
});

local task = BT.Task:new({
	name = "RunAway",

	start = function(self, obj)
	end,

	finish = function(self, obj)
	end,

	run = function(self, obj)
		print("Inside RunAway return success")
		self:success()
	end
});

bt:run()
```

I should really update the docs and examples so that people stop getting confused by this. It is a scoping issue, where success is defined.
